[package]
org = "ballerina"
name = "uuid"
version = "1.0.2"
authors = ["Ballerina"]
keywords = ["version", "unique"]
repository = "https://github.com/ballerina-platform/module-ballerina-uuid"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/uuid-native-1.0.2-SNAPSHOT.jar"
